import { Inter } from "next/font/google";
import "./globals.css";
//import Login from './pages/Login'
//import Register from "./pages/Register";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zinger Dashboard Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
